# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dylan_msc/obj.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class obj(genpy.Message):
  _md5sum = "39f905263ec0534b03a70af1d99b67f0"
  _type = "dylan_msc/obj"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 index
geometry_msgs/Point centroid
geometry_msgs/Point min
geometry_msgs/Point max
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['index','centroid','min','max']
  _slot_types = ['uint32','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       index,centroid,min,max

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obj, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.index is None:
        self.index = 0
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
    else:
      self.index = 0
      self.centroid = geometry_msgs.msg.Point()
      self.min = geometry_msgs.msg.Point()
      self.max = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I9d().pack(_x.index, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.index, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z,) = _get_struct_I9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I9d().pack(_x.index, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.centroid is None:
        self.centroid = geometry_msgs.msg.Point()
      if self.min is None:
        self.min = geometry_msgs.msg.Point()
      if self.max is None:
        self.max = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.index, _x.centroid.x, _x.centroid.y, _x.centroid.z, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z,) = _get_struct_I9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I9d = None
def _get_struct_I9d():
    global _struct_I9d
    if _struct_I9d is None:
        _struct_I9d = struct.Struct("<I9d")
    return _struct_I9d
